<!DOCTYPE html>
<html>
<head>
<title>OpenWanderer</title>
<style type="text/css">
body { font-family: helvetica, arial, sans-serif; }
#viewer { 
    width: 800px; 
    height: 600px; 
    border: 1px solid black;
}
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/plugins/markers.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/plugins/markers.js"></script>
<?php
$modes = ["basic" => 
            ["OpenWanderer", "The journey begins!"],
          "nav" => 
            ["OpenWanderer navigation demo", "Click the markers!"],
          "app" => 
            ["OpenWanderer example app", "A full example app with pano upload."]
        ];
$mode = isset($modes[$mode]) ? $mode: "basic";
?>
<script type='module' src='js/<?=$mode?>.js'></script>
</head>
<body>
<h1><?=$modes[$mode][0]?></h1>
<p><?=$modes[$mode][1]?></p>
<div id="pano" style="width: 800px; height: 600px"></div>
</body>
</html>
